config/routes.rb
Sshman::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}
  resources :users
  resources :keys, only: [:destroy]
  get '/sync_keys', to: 'users#merge_and_sync'
  authenticated :user do
    root :to => "users#show"
  end
  unauthenticated :user do
    root :to => "home#index", :as => :unauthenticated_root
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :authorizations, :dependent => :destroy

  def merge_and_sync
    authorizations.each do |auth|
      current_keys = auth.keys.map { |key| key.public_key.split(" ")[0..1].join(" ") } #make sure to compare the actual key, and not the email at the end if there 
      other_keys = Key.where.not(authorization: auth)
      # loop over our keys from other authorizations and add them in if they aren't in this auth
      other_keys.each do |missing_key|
        auth.clone_key missing_key unless current_keys.include? missing_key.public_key.split(" ")[0..1].join(" ")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    if params[:id]
      @user = User.find(params[:id]) 
    end
    @user ||= current_user
  end

  def merge_and_sync
    if params[:id]
      @user = User.find(params[:id]) 
    end
    @user ||= current_user
    @user.merge_and_sync
    flash[:success] = "All keys synced!"
    redirect_to @user
  end

end

app/views/users/index.html.slim
h3 Users
ul.users
  - @users.each do |user|
    li
      = link_to user.name, user
      | signed up #{user.created_at.to_date}

app/views/users/show.html.slim
h1
  =@user.name
h3 Link Additional Accounts
-Devise.omniauth_configs.keys.map {|k| k.capitalize.to_s }.each do |available_provider|
  =link_to available_provider, user_omniauth_authorize_path(:provider => available_provider.downcase), {:class => :btn}

br
br

=link_to "Merge and Sync all Keys", sync_keys_path, :class => [:btn, "btn-info"], :confirm => "Are you sure? This is irreversible"

h2 Keys
-@user.authorizations.each do |auth|
  h3
    =auth.provider
  -auth.keys.each do |key|
    =key.name
    =link_to "Delete Key", key, :method => :delete, :class => [:btn, "btn-danger"], :confirm => "Are you sure you want to delete key #{key.name}?"
    br
    pre.pre-scrollable
      =key.public_key